export default () => {
    return (
        <div>
            <div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div>
        <div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div><div>
            Course
        </div>
        </div>
    )
};